import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormBuilder, Validators} from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { PostService } from '../post.service';
import { IPost } from '../ipost';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';

import { WriterService } from 'src/app/entities/writer/writer.service';

@Component({
  selector: 'app-post-new',
  templateUrl: './post-new.component.html',
  styleUrls: ['./post-new.component.scss']
})
export class PostNewComponent extends BaseNewComponent<IPost> implements OnInit {
  
    title:string = "New Post";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<PostNewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public postService: PostService,
		public errorService: ErrorService,
		public writerService: WriterService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, postService, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'Post';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
    }
 		
	setForm(){
 		this.itemForm = this.formBuilder.group({
      body: ['', Validators.required],
      title: ['', Validators.required],
      writerDescriptiveField: [''],
    });
    
    this.fields = [
              {
      		  name: 'title',
      		  label: 'title',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'body',
      		  label: 'body',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
			{
				column: [
					{
						key: 'writerId',
						value: undefined,
						referencedkey: 'id'
					},
					  
				],
				isParent: false,
				table: 'writer',
				type: 'ManyToOne',
				service: this.writerService,
				label: 'writer',
				descriptiveField: 'writerDescriptiveField',
				referencedDescriptiveField: 'id',
		    
			},
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let post = this.itemForm.getRawValue();
		super.onSubmit(post);
		
	}
    
}
