import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';

import { MatDialog } from '@angular/material/dialog';

import { PostService } from '../post.service';
import { IPost } from '../ipost';

import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';

import { WriterService } from 'src/app/entities/writer/writer.service';

@Component({
  selector: 'app-post-details',
  templateUrl: './post-details.component.html',
  styleUrls: ['./post-details.component.scss']
})
export class PostDetailsComponent extends BaseDetailsComponent<IPost> implements OnInit {
	title = 'Post';
	parentUrl = 'post';
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public postService: PostService,
		public pickerDialogService: PickerDialogService,
		public errorService: ErrorService,
		public writerService: WriterService,
	) {
		super(formBuilder, router, route, dialog, pickerDialogService, postService, errorService);
  }

	ngOnInit() {
		this.entityName = 'Post';
		this.setAssociations();
		super.ngOnInit();
		this.setForm();
    	this.getItem();
	}
  
  setForm(){
    this.itemForm = this.formBuilder.group({
      body: ['', Validators.required],
      id: [{value: '', disabled: true}, Validators.required],
      title: ['', Validators.required],
      writerDescriptiveField : [''],
      
    });
    
    this.fields = [
        {
		  name: 'title',
		  label: 'title',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'body',
		  label: 'body',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
      ];
      
  }
  
  onItemFetched(item: IPost) {
    this.item = item;
     this.itemForm.patchValue(item);

  }
  
  setAssociations(){
    this.associations = [
      {
        column: [
	        {
	          key: 'writerId',
	          value: undefined,
	          referencedkey: 'id'
			},
		],
		isParent: false,
		table: 'writer',
		type: 'ManyToOne',
		label: 'writer',
		service: this.writerService,
		descriptiveField: 'writerDescriptiveField',
	    referencedDescriptiveField: 'id',
		},
		];
		
		this.childAssociations = this.associations.filter(association => {
			return (association.isParent);
		});

		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});
	}
	
	onSubmit() {
		let post = this.itemForm.getRawValue();
		super.onSubmit(post);
		
	}
}
